"use client";
import { useState } from "react";
import Section, { AMBER, CYAN, GREEN, PURPLE, Card } from "./Section";
import { LabFlags } from "./ChallengeMode";
import { Scores } from "./Certificate";
import { BOM_TOTAL } from "./data";

const SKILLS: { label: string; flag: keyof LabFlags | "always" }[] = [
  { label: "Robot chassis assembly & mechanical design", flag: "built" },
  { label: "Circuit wiring & schematic reading", flag: "wired" },
  { label: "Embedded C++ programming (Arduino/ESP32)", flag: "coded" },
  { label: "PID control theory & tuning", flag: "tuned" },
  { label: "Robot simulation & performance testing", flag: "simFinished" },
  { label: "IR sensor physics & digital logic", flag: "always" },
  { label: "H-bridge motor drivers & PWM", flag: "always" },
  { label: "Systematic hardware troubleshooting", flag: "always" },
];

const CONCEPTS = ["Closed-loop feedback control", "Differential drive kinematics", "PWM power modulation", "Sensor calibration & noise filtering", "Real-time embedded constraints", "Bang-bang vs PID controllers"];
const COMPONENTS_USED = ["ESP32 / Arduino Uno", "L298N dual H-bridge", "IR reflectance sensors ×2", "BO gear motors ×2", "Li-ion battery pack", "Acrylic chassis + caster"];

export default function Portfolio({ flags, scores, xp }: { flags: LabFlags; scores: Scores; xp: number }) {
  const [copied, setCopied] = useState<string | null>(null);

  const earnedSkills = SKILLS.filter((s) => s.flag === "always" || flags[s.flag as keyof LabFlags]);
  const dateStr = new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" });

  const portfolioMd = `# Project Portfolio — Autonomous Line Follower Robot

**Engineer:** _________________
**Completed:** ${dateStr} · APEX Academy Interactive Engineering Lab
**Session XP:** ${xp} · Skill ${scores.skill}/100 · Simulation ${scores.sim}/100 · Project ${scores.project}/100

## Project Summary
Designed, simulated, wired, programmed, and tuned a two-sensor autonomous
line-following robot based on a differential-drive chassis, an ESP32
microcontroller, an L298N H-bridge driver, and IR reflectance sensors.
Implemented both bang-bang and PID control firmware, tuned gains against
five virtual test tracks, and produced a complete real-world build plan
(BOM ₹${BOM_TOTAL}).

## Skills Demonstrated
${earnedSkills.map((s) => `- ${s.label}`).join("\n")}

## Engineering Concepts Mastered
${CONCEPTS.map((c) => `- ${c}`).join("\n")}

## Hardware Stack
${COMPONENTS_USED.map((c) => `- ${c}`).join("\n")}

## Code Written
- Arduino Uno bang-bang controller (C++, digital sensing, H-bridge control)
- ESP32 PID controller (C++, LEDC hardware PWM, anti-windup, derivative damping)

— Generated by APEX Academy · apexacademy.vercel.app/electronics/line-follower
`;

  const resumeBullets = `LINE FOLLOWER ROBOT — AUTONOMOUS SYSTEMS PROJECT (${dateStr})
• Built an autonomous differential-drive robot using ESP32, L298N motor driver, and IR reflectance sensors
• Implemented and tuned a PID control loop in embedded C++ achieving stable line tracking across 5 track profiles
• Designed the full power/signal architecture (16-connection schematic) and debugged it systematically
• Applied PWM motor control, sensor calibration, and noise filtering under real-time constraints`;

  const copy = (key: string, text: string) => {
    navigator.clipboard?.writeText(text).then(() => { setCopied(key); setTimeout(() => setCopied(null), 1600); });
  };

  const downloadMd = () => {
    const blob = new Blob([portfolioMd], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url; a.download = "apex-linefollower-portfolio.md"; a.click();
    URL.revokeObjectURL(url);
  };

  const linkedInUrl = `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent("https://apexacademy.vercel.app/electronics/line-follower")}`;

  return (
    <Section id="portfolio" num="17" title="Project Portfolio"
      subtitle="Everything you did here, packaged for the world — auto-generated from your actual progress in this session." color={PURPLE} wide>
      <div className="grid lg:grid-cols-3 gap-4">
        <Card className="p-5">
          <div className="text-[10px] font-black uppercase tracking-widest mb-3" style={{ color: GREEN }}>✓ Skills learned ({earnedSkills.length}/{SKILLS.length})</div>
          <div className="space-y-1.5">
            {SKILLS.map((s) => {
              const got = s.flag === "always" || flags[s.flag as keyof LabFlags];
              return (
                <div key={s.label} className="flex items-start gap-2 text-[11px] leading-snug"
                  style={{ color: got ? "rgba(255,255,255,0.65)" : "rgba(255,255,255,0.25)" }}>
                  <span style={{ color: got ? GREEN : "rgba(255,255,255,0.2)" }}>{got ? "✓" : "○"}</span>
                  {s.label}
                </div>
              );
            })}
          </div>
        </Card>

        <Card className="p-5">
          <div className="text-[10px] font-black uppercase tracking-widest mb-3" style={{ color: CYAN }}>⚙ Concepts mastered</div>
          <div className="space-y-1.5 mb-4">
            {CONCEPTS.map((c) => (
              <div key={c} className="text-[11px] text-white/55 leading-snug">• {c}</div>
            ))}
          </div>
          <div className="text-[10px] font-black uppercase tracking-widest mb-2" style={{ color: AMBER }}>🔩 Components used</div>
          <div className="flex flex-wrap gap-1.5">
            {COMPONENTS_USED.map((c) => (
              <span key={c} className="text-[10px] px-2 py-1 rounded-lg border border-white/10 text-white/45" style={{ background: "rgba(255,255,255,0.02)" }}>{c}</span>
            ))}
          </div>
        </Card>

        <Card className="p-5">
          <div className="text-[10px] font-black uppercase tracking-widest text-white/40 mb-3">Export & share</div>
          <div className="space-y-2">
            <button onClick={downloadMd}
              className="w-full text-left px-3.5 py-2.5 rounded-xl border border-white/10 text-xs font-bold text-white/60 hover:text-white hover:bg-white/5 transition-all">
              📁 Download Portfolio (.md) <span className="float-right text-white/25">↓</span>
            </button>
            <button onClick={() => copy("resume", resumeBullets)}
              className="w-full text-left px-3.5 py-2.5 rounded-xl border border-white/10 text-xs font-bold text-white/60 hover:text-white hover:bg-white/5 transition-all">
              {copied === "resume" ? "✓ Copied resume bullets!" : "📄 Copy resume bullets"}
            </button>
            <button onClick={() => copy("md", portfolioMd)}
              className="w-full text-left px-3.5 py-2.5 rounded-xl border border-white/10 text-xs font-bold text-white/60 hover:text-white hover:bg-white/5 transition-all">
              {copied === "md" ? "✓ Copied full portfolio!" : "📋 Copy portfolio text"}
            </button>
            <a href={linkedInUrl} target="_blank" rel="noopener noreferrer"
              className="block w-full text-left px-3.5 py-2.5 rounded-xl border text-xs font-bold transition-all hover:bg-white/5"
              style={{ borderColor: "#0A66C266", color: "#60A5FA" }}>
              💼 Share on LinkedIn <span className="float-right text-white/25">↗</span>
            </a>
          </div>

          <div className="mt-4 p-3 rounded-xl border text-center" style={{ borderColor: `${PURPLE}33`, background: `${PURPLE}0a` }}>
            <div className="text-[9px] uppercase tracking-widest text-white/30 mb-1">Session totals</div>
            <div className="flex justify-center gap-4 text-[11px]">
              <span><b style={{ color: AMBER }}>{xp}</b> <span className="text-white/35">XP</span></span>
              <span><b style={{ color: CYAN }}>{scores.sim}</b> <span className="text-white/35">sim</span></span>
              <span><b style={{ color: GREEN }}>{scores.project}</b> <span className="text-white/35">project</span></span>
            </div>
          </div>
        </Card>
      </div>
    </Section>
  );
}
