"use client";
import { useState } from "react";
import Section, { AMBER, CYAN, GREEN, Card } from "./Section";
import { BOM, BOM_TOTAL, ARDUINO_CODE, ESP32_CODE } from "./data";

function download(filename: string, content: string, mime = "text/plain") {
  const blob = new Blob([content], { type: `${mime};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

const ASSEMBLY_GUIDE = `APEX ACADEMY — LINE FOLLOWER ROBOT · ASSEMBLY GUIDE
=====================================================

STEP 1 — CHASSIS PREP (5 min)
  • Unpack the chassis kit; peel protective film from acrylic.
  • Identify motor slots (sides), caster hole (rear), sensor edge (front).

STEP 2 — DRIVETRAIN (15 min)
  • Bolt both BO motors into the side cutouts (wires facing inward/rear).
  • Push wheels onto the dual-flat shafts until they seat fully.
  • Screw the caster wheel to the rear center. Robot should sit level.

STEP 3 — POWER (10 min)
  • Stick the battery holder low and centered with double-sided tape.
  • Wire battery + through the rocker switch (cut the + lead, solder/screw both ends).
  • DO NOT insert cells yet.

STEP 4 — ELECTRONICS (15 min)
  • Mount L298N behind center; ESP32 on the front deck (USB port accessible).
  • Mount both IR sensors under the front edge, 3–8 mm above ground,
    spaced ~2–3 cm apart (just wider than your line).

STEP 5 — WIRING (20 min)  [full map in WIRING file]
  • IR VCC→3V3, GND→GND, OUT→GPIO34 (left) / GPIO35 (right)
  • ESP32 G25/26→IN1/IN2 · G27/14→IN3/IN4 · G32→ENA · G33→ENB (remove EN jumpers)
  • L298N OUT1/2→left motor, OUT3/4→right motor
  • Battery +→switch→12V, −→GND. L298N 5V→ESP32 VIN.
  • Double-check every ground is common!

STEP 6 — SMOKE TEST (5 min)
  • Wheels OFF the ground. Insert cells. Flip switch.
  • Driver LED on? ESP32 LED on? Nothing hot? Good.

STEP 7 — FLASH & CALIBRATE (15 min)
  • Upload the code (Arduino IDE → board: ESP32 Dev Module).
  • Calibrate each IR pot: LED ON over white, OFF over black.

STEP 8 — FIRST RUN
  • Build a track: black electrical tape on white chart paper, curves gentler
    than 15 cm radius to start.
  • Start at BASE_SPEED 140. Tune up from there. Happy engineering!

— Generated by APEX Academy · apexacademy.vercel.app/electronics/line-follower
`;

const WIRING_GUIDE = `APEX ACADEMY — LINE FOLLOWER · WIRING MAP
==========================================

IR SENSOR LEFT          ESP32
  VCC ─────────────────── 3V3
  GND ─────────────────── GND
  OUT ─────────────────── GPIO34

IR SENSOR RIGHT         ESP32
  VCC ─────────────────── 3V3
  GND ─────────────────── GND
  OUT ─────────────────── GPIO35

ESP32                   L298N
  GPIO25 ──────────────── IN1
  GPIO26 ──────────────── IN2
  GPIO27 ──────────────── IN3
  GPIO14 ──────────────── IN4
  GPIO32 ──────────────── ENA  (remove jumper cap)
  GPIO33 ──────────────── ENB  (remove jumper cap)
  VIN ─────────────────── 5V   (driver's regulator output)
  GND ─────────────────── GND

L298N                   MOTORS
  OUT1/OUT2 ───────────── LEFT MOTOR
  OUT3/OUT4 ───────────── RIGHT MOTOR

POWER
  BATTERY + ── SWITCH ─── L298N 12V
  BATTERY − ───────────── L298N GND (common ground!)

RULES
  1. ALL grounds connect together.
  2. Battery + always through the switch.
  3. If a motor spins backward, swap its OUT pair.
`;

export default function RealBuild() {
  const [copied, setCopied] = useState(false);

  const shoppingList = [
    "APEX ACADEMY — LINE FOLLOWER SHOPPING LIST",
    "=".repeat(44),
    ...BOM.map((i) => `[ ] ${i.qty}× ${i.name.padEnd(30)} ~₹${i.cost * i.qty}`),
    "-".repeat(44),
    `ESTIMATED TOTAL: ₹${BOM_TOTAL} (≈ $${Math.round(BOM_TOTAL / 84)})`,
    "",
    "Alternatives if out of stock:",
    ...BOM.map((i) => `  • ${i.name}: ${i.alt}`),
  ].join("\n");

  return (
    <Section id="real-build" num="15" title="Real Build Mode"
      subtitle="Ready to hold it in your hands? Complete parts list with live prices, purchase links, and every guide as a download." color={GREEN} wide>
      <div className="grid lg:grid-cols-[1fr_300px] gap-5">
        <Card className="overflow-hidden">
          <div className="grid grid-cols-[1fr_50px_70px_90px] gap-2 px-4 py-2.5 border-b border-white/8 text-[9px] font-black uppercase tracking-widest text-white/30">
            <span>Component</span><span className="text-center">Qty</span><span className="text-right">Cost</span><span className="text-right">Buy</span>
          </div>
          {BOM.map((i, idx) => (
            <div key={i.name} className="grid grid-cols-[1fr_50px_70px_90px] gap-2 px-4 py-2.5 items-center text-xs"
              style={{ background: idx % 2 ? "rgba(255,255,255,0.02)" : "transparent" }}>
              <div>
                <div className="font-bold text-white/70">{i.name}</div>
                <div className="text-[9px] text-white/30">alt: {i.alt}</div>
              </div>
              <span className="text-center font-mono text-white/50">{i.qty}</span>
              <span className="text-right font-mono font-bold" style={{ color: GREEN }}>₹{i.cost * i.qty}</span>
              <a href={`https://www.amazon.in/s?k=${encodeURIComponent(i.search)}`} target="_blank" rel="noopener noreferrer"
                className="text-right text-[10px] font-bold px-2 py-1 rounded-lg border transition-all hover:bg-white/5"
                style={{ borderColor: `${AMBER}44`, color: AMBER }}>
                Amazon ↗
              </a>
            </div>
          ))}
          <div className="flex justify-between items-center px-4 py-3 border-t border-white/8" style={{ background: `${GREEN}0a` }}>
            <span className="text-xs font-black text-white/60">ESTIMATED TOTAL</span>
            <span className="text-lg font-black font-mono" style={{ color: GREEN }}>₹{BOM_TOTAL} <span className="text-[10px] text-white/30">≈ ${Math.round(BOM_TOTAL / 84)}</span></span>
          </div>
        </Card>

        <div className="space-y-3">
          <Card className="p-4">
            <div className="text-[10px] font-black uppercase tracking-widest text-white/40 mb-3">Downloads</div>
            <div className="space-y-2">
              {[
                { label: "🛒 Shopping List (.txt)", fn: () => download("apex-linefollower-shopping-list.txt", shoppingList) },
                { label: "📋 Assembly Guide (.txt)", fn: () => download("apex-linefollower-assembly-guide.txt", ASSEMBLY_GUIDE) },
                { label: "🔌 Wiring Diagram (.txt)", fn: () => download("apex-linefollower-wiring.txt", WIRING_GUIDE) },
                { label: "💻 Arduino Uno Code (.ino)", fn: () => download("linefollower_uno.ino", ARDUINO_CODE) },
                { label: "🧠 ESP32 PID Code (.ino)", fn: () => download("linefollower_esp32.ino", ESP32_CODE) },
              ].map((d) => (
                <button key={d.label} onClick={d.fn}
                  className="w-full text-left px-3.5 py-2.5 rounded-xl border border-white/10 text-xs font-bold text-white/60 hover:text-white hover:bg-white/5 transition-all">
                  {d.label} <span className="float-right text-white/25">↓</span>
                </button>
              ))}
            </div>
          </Card>

          <Card className="p-4">
            <div className="text-[10px] font-black uppercase tracking-widest text-white/40 mb-2">Budget hacks</div>
            <ul className="text-[11px] text-white/45 space-y-1.5 leading-snug">
              <li>• A &quot;2WD smart car kit&quot; bundles chassis + motors + wheels + caster for ~₹450 — cheaper than separates.</li>
              <li>• Cardboard chassis works for a first prototype. Really.</li>
              <li>• Black electrical tape on the back of white flex-banner = free competition-grade track.</li>
              <li>• Skip the ESP32 if you already own an Uno — the Arduino tab in Code Lab is drop-in ready.</li>
            </ul>
          </Card>

          <button
            onClick={() => { navigator.clipboard?.writeText(shoppingList).then(() => { setCopied(true); setTimeout(() => setCopied(false), 1600); }); }}
            className="w-full py-3 rounded-xl font-black text-xs transition-all"
            style={{ background: copied ? `${GREEN}22` : `linear-gradient(90deg, ${GREEN}, ${CYAN})`, color: copied ? GREEN : "#04120D" }}>
            {copied ? "✓ Copied to clipboard!" : "📋 Copy shopping list"}
          </button>
        </div>
      </div>
    </Section>
  );
}
