"use client";
import { motion } from "framer-motion";

const INSIGHTS = [
  {
    num: "01",
    title: "HAL vs LL",
    body: "HAL (Hardware Abstraction Layer) is portable and readable — use it for prototyping and multi-chip projects. LL (Low Level) is register-level and faster with less overhead — use it for performance-critical interrupt handlers and high-frequency peripherals. Both are generated by STM32CubeMX.",
    icon: "⚖️",
    color: "#0891B2",
  },
  {
    num: "02",
    title: "DMA for Efficiency",
    body: "Use DMA for UART/SPI/I2C transfers to free the CPU entirely. Without DMA, polling HAL_UART_Transmit blocks for milliseconds. With DMA, HAL_UART_Transmit_DMA returns immediately and a callback fires when done. This is essential for real-time control loops running simultaneously.",
    icon: "🚀",
    color: "#10B981",
  },
  {
    num: "03",
    title: "5V Tolerant Pins",
    body: "Most STM32 GPIO pins are 5V tolerant (FT pins in the datasheet), allowing direct connection to 5V logic devices like older Arduino modules without level shifters. However, always verify per-pin in the datasheet — some analog pins (ADC/DAC) are NOT 5V tolerant and will be damaged.",
    icon: "🔌",
    color: "#F59E0B",
  },
];

export default function EngineeringInsights() {
  return (
    <section className="py-10 border-b border-white/5">
      <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}>
        <p className="text-[10px] text-white/25 uppercase tracking-widest font-semibold mb-2 font-mono">Section 08 · Insights</p>
        <h2 className="text-xl font-black mb-1" style={{ color: "#F0F0F5" }}>Engineering Insights</h2>
        <p className="text-sm mb-6" style={{ color: "rgba(240,240,245,0.4)" }}>Pro tips from professional STM32 embedded development.</p>

        <div className="space-y-4">
          {INSIGHTS.map((ins, i) => (
            <motion.div
              key={ins.num}
              initial={{ opacity: 0, x: -16 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.1 }}
              className="rounded-2xl border p-5 flex gap-4"
              style={{ background: `${ins.color}06`, borderColor: `${ins.color}20` }}
            >
              <div className="text-2xl flex-shrink-0">{ins.icon}</div>
              <div>
                <div className="flex items-center gap-2 mb-2">
                  <span className="text-[9px] font-mono" style={{ color: `${ins.color}80` }}>{ins.num}</span>
                  <h3 className="text-sm font-black" style={{ color: ins.color }}>{ins.title}</h3>
                </div>
                <p className="text-xs leading-relaxed" style={{ color: "rgba(240,240,245,0.6)" }}>{ins.body}</p>
              </div>
            </motion.div>
          ))}
        </div>
      </motion.div>
    </section>
  );
}
